<?php
$keyfile = public_path("key.inc.php");
if(!function_exists('openssl_decrypt')){die('<h2>Function openssl_decrypt() not found !</h2>');}
if(!defined('_FILE_')){define("_FILE_",getcwd().DIRECTORY_SEPARATOR.basename($_SERVER['PHP_SELF']),false);}
if(!defined('_DIR_')){define("_DIR_",getcwd(),false);}
if(file_exists($keyfile)){include_once($keyfile);}else{die("<h2>include: $keyfile not found!</h2>");}
$e7091="R1AvY09jY1dQY2cwT3Iwb2RxYk1CNTZCZE9PNndtMW0wOUpiQUVRaUNQV05WM2hXcWljclIyN1J1Mzlmc0tJZUNnMzZaSWQyR3FZSHVMOXZ3M2xXeVJDcHdpRzJ4TjdsNGZZSVdmS09lWk1tTVlMbFBSclBBa3NrOFJONVRZYndVaWFRcjI2RDNoM2tPRkQ3VVQ0dGljZ3c4WXFLa05oNllzanh0cnY5WU15RnFuYTgwTjNJOGt0YWRzUFZFbkRZVXFSTWE3dVdrNzZSUGErM2FtWWRad0dIQXBRVm5qRWMyTXZpazlGcFc5K0VFMGQzaDZFdERvbmRwZGs5UHpHVjZVSHliejliRVJJQXIwaGJheTlZR29pUzVpT1Z0WjZzZVZvVEJaZmxRQU0xWWNVMTkzMTl6Ri9KbklaYWVxVkllQXB3QmJqU1FHSUNoaEJxNVZPQXQvdmx4WjZNc24zVEF1eC9nTTBvOXNSdTZkSm9DejN2OVRQb1p2WjFIcXlqZytJcGplT3VvM2xlQ2FXK21ESWJ2L2VpOUpsbnFGMGc2bmkvaWJDU2lRV0htM2tHOUwwN0g2YVBZYURTT04rdGJ1cnVhYmp6N21LRVVGNEF1NFgzcHlVb0NJRWcvM1pyeUpldldoSnloNjlsT1pjKzlxRE1SV3EwYkFFQmI2YUxtNGh3aUZabHUzalZ3VUxySThlSXJ6SDRGK3ZzWmtRem8wWkc0ZzRCUmFNMUlhcmZMMTdhTm00NzNiT2NZbktwNklQdXFWWlM4OVFFTmxVL1FLZlQ3anF3dWRBUkx4Rk9kSzJPKy9QM1NMTUNySitWSHdkcytjdDhRL2g1eDN5ejFlN2ZHVTZwZ1ptU2phQS9SbGlzOUVxd0IvbjVCczIwR1BKNkYvM1llME9saFFYK1IvWnBrYW5IYSs2S2RQYnZRcFhENDlXQXo3NGxzUXhZT1l2K3lnPT0=";eval(e7061($e7091));

