<?php
namespace App\Helper;

class Vars
{
    const ADMIN_ROUTE = "838v7aozgk",
        ADVERTISER_ROUTE = "advertiser",
        PUBLISHER_ROUTE = "publisher",
        BASIC_INFO = "basic_info",
        COMPANY_INFO = "company_info",
        LOGIN_INFO = "login_info",
        API_INFO = "api_info",
        WEBSITES = "websites",
        BILLING_INFO = "billing_info",
        PAYMENT_SETTINGS = "payment_settings",
        GLOBAL = "global",
        AWIN = "Awin",
        ADMITAD = "Admitad",
        COMMISSION_FACTORY = "Commission Factory",
        IMPACT_RADIUS = "Impact",
        LINKCONNECTOR = "Link Connector",
        QUK = "Quk",
        PARTNERIZE = "Partnerize",
        PEPPERJAM = "Pepperjam",
        ECLICK = "Eclick",
        SALESGAIN = "SalesGain",
        RAKUTEN = "Rakuten",
        SHAREASALE = "Shareasale",
        TAKEADS = "Takeads",
        TRADEDOUBLER = "Tradedoubler",
        WEBGAINS = "Webgains",
        COMMISSION_PERCENTAGE = 80,
        COMMISSION_LINKSCIRCLE = "Revshare 80",
        OPTIMISE = 'OptimiseMedia',
        ADVERTISER = "advertiser",
        ADVERTISER_DETAIL = "advertiser_detail",
        COUPON = "coupon",
            TRANSACTION = "transaction",
            DUOMAI = 'Duomai',
        TRANSACTION_SHORT = "transaction_short",
        PAYMENT = "payment",

        LIST = [
            self::ADMITAD,
            self::AWIN,
            self::COMMISSION_FACTORY,
            self::IMPACT_RADIUS,
            self::LINKCONNECTOR,
            self::PARTNERIZE,
            self::PEPPERJAM,
            self::RAKUTEN,
            self::SHAREASALE,
            self::TRADEDOUBLER,
            self::TAKEADS,
            self::WEBGAINS,
             self::QUK,
              self::OPTIMISE,
             self::ECLICK,
             self::DUOMAI,
             self::SALESGAIN
        ],

        OPTION_LIST = [
            self::ADMITAD,
             self::AWIN,
             self::IMPACT_RADIUS,
            // self::LINKCONNECTOR,
             self::PARTNERIZE,
             self::PEPPERJAM,
            // self::RAKUTEN,
             self::TRADEDOUBLER,
            // self::TAKEADS,
            self::ECLICK,
             self::QUK,
              self::OPTIMISE,
             self::DUOMAI,
             self::SALESGAIN
        ],

        OFFSET_0 = 0,
        LIMIT_1 = 1,
        LIMIT_2 = 2,
        LIMIT_5 = 5,
        LIMIT_10 = 10,
        LIMIT_20 = 20,
        LIMIT_30 = 30,
        LIMIT_40 = 40,
        LIMIT_50 = 50,
        LIMIT_100 = 100,
        LIMIT_200 = 200,
        LIMIT_300 = 300,
        LIMIT_400 = 400,
        LIMIT_500 = 500,
        LIMIT_1000 = 1000,
        LIMIT_2000 = 2000,
        LIMIT_3000 = 3000,
        LIMIT_4000 = 4000,
        LIMIT_5000 = 5000,
        AWIN_ADVERTISER_LIMIT = 500,
        AWIN_ADVERTISER_EXTRA_LIMIT = 15,
        AWIN_TRANSACTION_LIMIT = 20,
        ADMITAD_CATEGORIES_LIMIT = 200,
        ADMITAD_PROMOTIONAL_METHOD_LIMIT = 200,
        ADMITAD_ADVERTISER_LIMIT = 200,
        ADMITAD_COUPON_LIMIT = 200,
        ADMITAD_TRANSACTION_LIMIT = 20,
        IMPACT_TRANSACTION_LIMIT = 20,
        DEFAULT_PUBLISHER_ADVERTISER_PAGINATION = 20,
        DEFAULT_PUBLISHER_TRANSACTION_PAGINATION = 10,
        DEFAULT_PUBLISHER_PAYMENT_PAGINATION = 10,
        DEFAULT_PUBLISHER_EARNING_PERFORMANCE_PAGINATION = 10,
        DEFAULT_PUBLISHER_CONVERSION_PERFORMANCE_PAGINATION = 10,
        DEFAULT_PUBLISHER_COUPON_PAGINATION = 10,
        DEFAULT_PUBLISHER_TEXT_LINKS_PAGINATION = 10,
        DEFAULT_PUBLISHER_DEEP_LINKS_PAGINATION = 10,
        PUBLISHER_ADVERTISER_LIST_VIEW = "list",
        PUBLISHER_ADVERTISER_BOX_VIEW = "box",
        TEMP_TRANSACTION = "temp_transaction",
        SEND_EMAIL = "email_jobs",
        ADMIN_WORK = "admin_work",
        EXTRA_WORK = "extra_work",
        GENERATE_EXPORT = "generate_export",
        LINK_GENERATE = "link_generate",
        MAKE_HISTORY = "make_history",
        FETCH_MEDIA = "media",
        ADMITAD_ON_QUEUE = "admitad_data",
        ADMITAD_TRANSACTION_ON_QUEUE = "admitad_trans",
        AWIN_ON_QUEUE = "awin_data",
        AWIN_TRANSACTION_ON_QUEUE = "awin_trans",
        PEPPERJAM_ON_QUEUE = "pepperjam_data",
        PEPPERJAM_TRANSACTION_ON_QUEUE = "pepperjam_trans",
        IMPACT_RADIUS_ON_QUEUE = "impact_data",
        IMPACT_RADIUS_TRANSACTION_ON_QUEUE = "impact_trans",
        LINK_CONNECTOR_ON_QUEUE = "linkconnector_data",
        LINK_CONNECTOR_TRANSACTION_ON_QUEUE = "linkconnector_trans",
        RAKUTEN_ON_QUEUE = "rakuten_data",
        RAKUTEN_TRANSACTION_ON_QUEUE = "rakuten_trans",
        TRADEDOUBLER_ON_QUEUE = "tradedoubler_data",
        TRADEDOUBLER_TRANSACTION_ON_QUEUE = "tradedoubler_trans",
        CRON_JOB_CREATED = "Cron Job Created",
        DEFAULT_GENERATED = "Default Generated",
        ADVERTISER_NOT_AVAILABLE = 0,
        ADVERTISER_AVAILABLE = 1,
        ADVERTISER_STATUS_PENDING = 0,
        ADVERTISER_STATUS_ACTIVE = 1,
        ADVERTISER_STATUS_NOT_FOUND = 2,
        NEW_NOTIFICATION = 1,
        PAYPAL = 'paypal',
        PAYONEER = 'payoneer',
        BANKWIRE = 'bank-wire',
        BANK = 'bank',
        CUSTOM_DATE_FORMAT = "Y-m-d H:i",
        CUSTOM_DATE_FORMAT_2 = "Y-m-d H:i:s",
        CUSTOM_DATE_FORMAT_3 = "Y-m-d",
        JOB_STATUS_IN_PROCESS = 1,
        JOB_STATUS_COMPLETE = 0,
        JOB_ACTIVE = 1,
        JOB_IN_PROCESS = 2,
        JOB_NOT_PROCESS = 0,
        JOB_ERROR = 3,
        JOB_NULL = null,
        TRACKING_LINK_REMOVE_FIELDS = [
            'categories',
            'supported_regions',
            'average_payment_time',
            'validation_days',
            'epc',
            'tags',
            'offer_type',
            'logo',
            'fetch_logo_url',
            'company_name',
            'phone_number',
            'address',
            'city',
            'country',
            'state',
            'exclusive',
            'primary_regions',
            'country_full_name',
            'valid_domains',
            'type',
            'program_restrictions',
            'promotional_methods',
            'deleted_at',
            'description',
            'short_description',
            'program_policies'
        ],
        SYNC = 1,
        NOT_SYNC = 0;
}
